In [1]:
# cleans up courseassessmentreviews
import pandas as pd
courseassessmentdb = pd.read_csv('../data/course_assessment_reviews.csv')
courseassessmentdb

,Term,Review,Department,Course Name,Prof Name
0,Fall Term 2018,"Perfect pace, syllabus, and content.",AAAS,AAAS 39.02: History of Jazz since 1959,Donald Glasgo
1,Fall Term 2018,The listening quizzes were effective in that t...,AAAS,AAAS 39.02: History of Jazz since 1959,Donald Glasgo
2,Fall Term 2019,"The workload was very manageable, and the quiz...",AAAS,AAAS 39.02: History of Jazz since 1959,Donald Glasgo
3,Fall Term 2019,"liked the variation in tests, journals, and pe...",AAAS,AAAS 39.02: History of Jazz since 1959,Donald Glasgo
4,Fall Term 2019,quizzes and final project,AAAS,AAAS 39.02: History of Jazz since 1959,Donald Glasgo
...,...,...,...,...,...
56922,Spring Term 2019,I enjoyed the course and learned a lot about h...,WRIT,WRIT 07.24: Past Imperfect,Cynthia Monroe
56923,Spring Term 2019,I think of and read history in a new way now. ...,WRIT,WRIT 07.24: Past Imperfect,Cynthia Monroe
56924,Spring Term 2019,It made me like studying history a bit more.,WRIT,WRIT 07.24: Past Imperfect,Cynthia Monroe
56925,Spring Term 2019,It made me more optimistic. I found the Profes...,WRIT,WRIT 07.24: Past Imperfect,Cynthia Monroe
56926,Spring Term 2019,Not a lot,WRIT,WRIT 07.24: Past Imperfect,Cynthia Monroe

In [2]:
# reformats the term to match with LayupList term format
def clean_term(row):
    term_info = row['Term'].split(' ')
    
    # changes ending from S to X based on summer term
    if term_info[0] != 'Summer':
        return term_info[2][2:] + term_info[0][0]
    else:
        return term_info[2][2:] + 'X'
    
courseassessmentdb['Term'] = courseassessmentdb.apply(clean_term, axis = 1)
courseassessmentdb

,Term,Review,Department,Course Name,Prof Name
0,18F,"Perfect pace, syllabus, and content.",AAAS,AAAS 39.02: History of Jazz since 1959,Donald Glasgo
1,18F,The listening quizzes were effective in that t...,AAAS,AAAS 39.02: History of Jazz since 1959,Donald Glasgo
2,19F,"The workload was very manageable, and the quiz...",AAAS,AAAS 39.02: History of Jazz since 1959,Donald Glasgo
3,19F,"liked the variation in tests, journals, and pe...",AAAS,AAAS 39.02: History of Jazz since 1959,Donald Glasgo
4,19F,quizzes and final project,AAAS,AAAS 39.02: History of Jazz since 1959,Donald Glasgo
...,...,...,...,...,...
56922,19S,I enjoyed the course and learned a lot about h...,WRIT,WRIT 07.24: Past Imperfect,Cynthia Monroe
56923,19S,I think of and read history in a new way now. ...,WRIT,WRIT 07.24: Past Imperfect,Cynthia Monroe
56924,19S,It made me like studying history a bit more.,WRIT,WRIT 07.24: Past Imperfect,Cynthia Monroe
56925,19S,It made me more optimistic. I found the Profes...,WRIT,WRIT 07.24: Past Imperfect,Cynthia Monroe
56926,19S,Not a lot,WRIT,WRIT 07.24: Past Imperfect,Cynthia Monroe

In [3]:
courseassessmentdb.to_csv('../data/course_assessment_cleaned.csv')